### PR TITLE
Upgrade to react 16

### PR DESCRIPTION
**Pull request by dleroux**
Since V2 will require react 16 I needed it to be updated to test a change. 

Looks like this was all that was needed. Is that right?

### CODE REVIEW

**Comment by AWaselnuk** [comment]
@dleroux did you successfully run the app as `v16.2` to test out your change?

**Comment by dleroux** [comment]
Looks like it did. I almost don't believe it was that easy :) If you can try do that would be great.

**Comment by buggy** [comment]
React 16 is almost a drop in replacement for 15. You might want to implement an error boundary to display a friendly error message and prevent the application unmounting when something goes wrong.

**Comment by AWaselnuk** [comment]
@dleroux do you want to take at stab at @buggy suggestion? We can put the boundary at the app root and make it very generic since we don't have much of a UI demo at the moment.

**Pull request merged**
